# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': '邮箱验证', 'verbose_name_plural': '邮箱验证'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(max_length=200, upload_to='static/banner/%Y/%m', verbose_name='轮播图片'),
        ),
    ]
