# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181207_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='expired_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 16, 43, 53, 442466)),
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
